# Generated by Django 2.1.2 on 2019-04-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdatas', '0004_auto_20190422_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='response1',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='response2',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='response3',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='response4',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='response5',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='response6',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
