# Generated by Django 2.1.2 on 2019-04-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdatas', '0005_auto_20190424_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='spiral_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='tremor_test',
            field=models.BooleanField(default=False),
        ),
    ]
